spring.application.name=progress_checker

# spring.datasource.url=jdbc:mysql://localhost:3306/progress_checker_for_cbc?createDatabaseIfNotExist=true
spring.datasource.url=jdbc:mysql://mysql-357b8c0c-mureithieugene739-01fd.k.aivencloud.com:25883/defaultdb
#spring.datasource.username=root
spring.datasource.username=avnadmin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.password=muresh78
 spring.datasource.password=AVNS_dxiN6zq3QvfkOdlTHt1
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
 spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
#spring.sql.init.mode=never
#spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.mail.host=smtp.gmail.com

spring.mail.port=587
spring.mail.username=mureithieugene730@gmail.com
spring.mail.password=iwtn kyha gxkk dvwj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# JWT settings
jwt.secret=MineCarsMineCarsMineCarsMineCarsMineCarsMineCarsMineCarsMineCarsMineCarsMineCarsMineCarsMineCarsMineCarsMineCarsMineCars
 #jwt.expiration=3600000  
# 1 hour in milliseconds
